experiment_name: classification_spokenarabicdigits_dlinear
experiment_overwrite: true
seed: 2026
model_name: dlinear
dataset_name: spokenarabicdigits
loss_name: ce
optim_name: adam

task:
  classification:
    seq_len: 93

data:
  split:
    train: 0.8
    val: 0.2
    test: 0.0
  use_train_val_split: false
  loader:
    batch_size: 64
    num_workers: 2
    persistent_workers: true
    train:
      drop_last: false
    eval:
      drop_last: false

model:
  dlinear:
    name: dlinear
    task_name: classification
    enc_in: 13
    seq_len: 93
    pred_len: 93
    moving_avg: 25
    individual: false
    num_class: 10

dataset:
  spokenarabicdigits:
    name: spokenarabicdigits
    root: datasets/SpokenArabicDigits
    train_path: SpokenArabicDigits_TRAIN.ts
    test_path: SpokenArabicDigits_TEST.ts
    max_seq_len: 93
    num_features: 13
    num_classes: 10
    normalize: true
    flatten: false
    infer_data_path: null

loss:
  ce:
    name: ce

optim:
  adam:
    lr: 1e-3
    weight_decay: 0.0

trainer:
  max_epochs: 10
  min_epochs: 1
  accelerator: auto
  devices: 1
  precision: 32

callbacks:
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 10
    min_delta: 0.0

  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 0
    save_last: true
    save_weights_only: false
    every_n_epochs: null
    every_n_train_steps: null
    train_time_interval: null
