experiment_name: forecast_ett-small_dlinear
experiment_overwrite: true
seed: 2026
model_name: dlinear
dataset_name: ett-small
loss_name: mse
optim_name: adam

task:
  forecast:
    seq_len: 96
    label_len: 0
    pred_len: 24
    scale: true
    timeenc: 0
    time_features: false

data:
  split:
    train: 0.7
    val: 0.2
    test: 0.1
  loader:
    batch_size: 32
    num_workers: 2
    persistent_workers: true
    train:
      drop_last: true
    eval:
      drop_last: false

model:
  dlinear:
    name: dlinear
    task_name: forecast
    enc_in: 7
    seq_len: 96
    pred_len: 24
    moving_avg: 25
    individual: false

dataset:
  ett-small:
    name: ett-small
    root: datasets/ETT-small
    data_path: ETTh1.csv
    infer_data_path: datasets/ETT-small/ETTh2.csv
    split_mode: tsl
    schema:
      date_col: date
      target: OT
      features: M
      freq: h

loss:
  mse:
    name: mse

optim:
  adam:
    lr: 1e-3
    weight_decay: 0.0

trainer:
  max_epochs: 10
  min_epochs: 1
  accelerator: auto
  devices: 1
  precision: 32

callbacks:
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 10
    min_delta: 0.0

  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 0
    save_last: true
    save_weights_only: false
    every_n_epochs: null
    every_n_train_steps: null
    train_time_interval: null
