paths:
  experiments_dir: experiments
  results_dir: results

preprocess_name: mock

preprocess:
  mock:
    root: datasets/mock
    raw_dir: data/raw1
    out_dir: data/processed1
    train_size: 256
    val_size: 64
    test_size: 64
    num_features: 32
    num_classes: 10

callbacks:
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 10
    min_delta: 0.0

  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 1
    save_last: true
    save_weights_only: false
    every_n_epochs: null
    every_n_train_steps: null
    train_time_interval: null

logging:
  use_wandb: false
  project: ts_proj
